title:              Moosetechnology
email:              https://sympa.inria.fr/sympa/subscribe/moose
description:        Analyse and model your software system
author:             Moosetechnology
baseurl:            
url:                "https://moosetechnology.github.io"

twitter_username:   moosetechnology
github_username:    moosetechnology

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-spaceship
