title:              Moosetechnology
email:              https://sympa.inria.fr/sympa/subscribe/moose
description:        Analyse and model your software system
author:             Moosetechnology
baseurl:            "/"
url:                "https://modularmoose.org"

twitter_username:   moosetechnology
github_username:    moosetechnology

collections:
  posts:
    output: true
    permalink: /:collection/:name

tag_page_layout: tag_page
tag_page_dir: posts/tag
tag_permalink_style: pretty

# Build settings
markdown:           kramdown
highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-spaceship
  - jekyll-seo-tag
